### ISSUE TITLE
Fetch versions from iojs.org?

### ISSUE THREAD

**Issue by phillipj** [evanlucas/iojs-versions#1]
Have you considered fetching versions from iojs.org's [index.json](https://iojs.org/dist/index.json)?

I'm currently thinking about extracting the "logic" surrounding URLs on nodejs.org's [downloads page](https://github.com/nodejs/new.nodejs.org/blob/master/layouts/download.hbs#L42) and the [release blog post](https://github.com/nodejs/new.nodejs.org/blob/master/locale/en/blog/release/v0.12.7.md). The `index.json` on iojs.org (and nodejs.org) has a low level representation of which files are available per release, which is great for my use case atleast, which I would have to decorate with some extra human readable title/descriptions.

By fetching data from iojs.org and nodejs.org you wouldnt have to update this package every time a new release comes and more meta data would be available. The biggest downside being you would actually have to perform a HTTP request and suddenly are reliant on iojs.org being available.

**Comment by evanlucas** [comment]
Yea, that is the main reason I went this route...to avoid making an HTTP request.

**Comment by phillipj** [comment]
Fully understandable. I'll close this and think of doing something custom.

**Comment by evanlucas** [comment]
Is there a use case that you need the additional metadata for? I'd be open to changing that if so :]

**Comment by phillipj** [comment]
I would like to reproduce the download matrix and release blog post with that data, meaning the hard coded items and URLs in markup and markdown could be replaced by looping over that data. The main reason for doing this would be re-usability and less error prone.

**Comment by evanlucas** [comment]
Feel free to open a PR. Anything I can help with?

**Comment by phillipj** [comment]
Thanks! I'll open a PR and let you know, feedback then would have been great.

**Comment by evanlucas** [comment]
Apologies. I should have read the initial description more thoroughly. I swear I'm never going to reply from my phone again :]

**Comment by phillipj** [comment]
Haha, no worries :)
